### ISSUE TITLE
Change timestamp format in responses

### ISSUE THREAD

**Issue by israellevin** [paket-core/webserver#6]
Flask's jsonify turns datetime into RFC 1123. It's human readable, but it's not iso 8601 (the recommended human readable format) and it's not unix timestamp (which is the way we take timestamps as input, and also the universal constant of truth and beauty). We should probably change it into one of them.

**Comment by yaroslavr-itd** [comment]
Done in [453886f](https://github.com/paket-core/webserver/commit/453886f8b5c6ae29c6e233359bafc080f987d333)
